<a href="https://colab.research.google.com/github/ks-yahagi/EU_M_Math-Repository/blob/main/Chap02_Ex_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy.linalg as linalg

data=np.array([[1,2,3],[1,3,2],[3,1,2]])

inv_mat=linalg.inv(data)
eig_value,eig_vector=linalg.eig(data)

print("逆行列:",inv_mat)
print("固有値:",eig_value)
print("固有値ベクトル:",eig_vector)

逆行列: [[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
固有値: [ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
固有値ベクトル: [[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]
